### ISSUE TITLE
DNS is not set in VPC Subnet

### ISSUE THREAD

**Issue by alwinmark** [opentelekomcloud/kontainer-engine-driver-otc#40]
According to:  OTC Probleme // IM0032219586
When one creates a new VPC with Subnet (or just a new Subnet), the DNS server entry stays empty.
This causes the cloud init script to fail so the worker nodes never become active.

Currently to mitigate this issue manually is (re)setting the DNS Settings on the Subnet.

**Comment by anton-sidelnikov** [comment]
Fixed, just clear browser cache for rancher ui and try to create cluster.
