### ISSUE TITLE
Add ability to authenticate with access key

### ISSUE THREAD

**Issue by jwinkelmann97** [opentelekomcloud/kontainer-engine-driver-otc#41]
Hi there,

Is it possible to add the ability to authenticate with access keys? I would need this feature because 2fa is enabled.

Regards

Jan

**Comment by outcatcher** [comment]
Hi, @jwinkelmann97 do you want to use permanent AK/SK or temporary AK/SK (AK/SK + security token)?

**Comment by outcatcher** [comment]
Done in https://github.com/opentelekomcloud/ui-cluster-driver-otc/pull/64
Merged into `rancher:master` in https://github.com/rancher/rancher/pull/32790
