### ISSUE TITLE
Dropdowns "Node Flavor" and "SSH Key Pair" not being populated

### ISSUE THREAD

**Issue by sphr2k** [opentelekomcloud/kontainer-engine-driver-otc#42]
I'm trying to set up an OTC cluster from Rancher. Everything seems ok up to the point where I would select the _Node Flavor_ and the _SSH Key Pair_. These two drowdowns are not being populated.

* Rancher v2.5.8
* Open Telekom Cloud CCE driver 1.0.2
* OTC user w/ full admin rights

**Comment by outcatcher** [comment]
@sphr2k are there any errors in the console? I can see there is a flavor list broken because of some strange `s3ebackup.2xlarge.2` flavor in the list, but it should be okay for the key pairs.

**Comment by outcatcher** [comment]
@sphr2k 
Please try to use the following `component.js`:
https://otc-rancher.obs.eu-de.otc.t-systems.com/cluster/ui/v1.1.1-rc1/component.js

Now it should work.

**Comment by sphr2k** [comment]
Thanks, working fine now. SSH keys were fine before, I was just unaware that these are user-specific.

**Comment by outcatcher** [comment]
That's not user-specific, it reproduces for everyone. This flavor just wasn't in the list previously :slightly_smiling_face: We will test the new release and make a PR to the Rancher.
