### ISSUE TITLE
Support for eu-ch2 region

### ISSUE THREAD

**Issue by tervor** [opentelekomcloud/kontainer-engine-driver-otc#50]
Can you please add support for the eu-ch2 region?
The eu-ch2 region uses a different authentication url from the eu-de2 region, but it can not be specified during cluster creation.
The authentication endpoint for eu-ch2 is https://iam-pub.eu-ch2.sc.otc.t-systems.com/v3.

When trying to deploy a cluster the following error message is shown which shows the hard-coded eu-de auth url:
```
HTTPError: HTTP error received. 401 Unauthorized: {"message":"Authorization information is wrong","request_id":"7fbe494479d16097a8136e37bb5b1736"} Request Opts: {"method":"GET","url":"https://rancher-test.t-systems.ch/meta/proxy/iam.eu-de.otc.t-systems.com/v3/projects?name=eu-ch2_tos-mgmt","headers":{"accept":"application/json","content-type":"application/json","host":"iam.eu-de.otc.t-systems.com","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0","x-api-auth-header":"SDK-HMAC-SHA256 Credential=dfsd/20230425///sdk_request, SignedHeaders=accept;content-type;host;user-agent;x-sdk-date, Signature=0437b54ffb67c842dcb06d4480445fc65f6f25c6ef8297e00f91f1d1b974990d","x-sdk-date":"20230425T120407Z"},"params":{"name":"eu-ch2_tos-mgmt"},"schema":{},"baseURL":""}
```

**Comment by tervor** [comment]
We meanwhile dug a bit our-self and replaced the Custom UI URL for the Open Telekom Cloud CCE plugin in the rancher UI with our modified version of the component.js (component.js in the diff below), based on https://otc-rancher.obs.eu-de.otc.t-systems.com/cluster/ui/v1.1.0/component.js (component_otc_1.1.0.js in the diff).
We managed to debug further, but are unable to select a node flavor because the drop-down is empty. We also get the following error in the browsers console:


![Screenshot 2023-04-25 at 16 53 03](https://user-images.githubusercontent.com/1598708/234316780-51bbb6f9-9f17-4826-b5da-a542c5b69c88.png)

```diff
$ diff component_otc_1.1.0.js component.js
21c21
<     const authURL = 'https://iam.eu-de.otc.t-systems.com/v3';
---
>     const authURL = 'https://iam-pub.eu-ch2.sc.otc.t-systems.com/v3';
39,41c39,41
<     const os = "EulerOS 2.5";
<     const diskTypes = ['SATA', 'SAS', 'SSD'];
<     const availabilityZones = ['eu-de-01', 'eu-de-02', 'eu-de-03'];
---
>     const os = "EulerOS 2.9";
>     const diskTypes = ['SAS', 'SSD'];
>     const availabilityZones = ['eu-ch2a', 'eu-ch2b'];
136c136
<                 projectName: field('Project Name', 'eu-de'),
---
>                 projectName: field('Project Name', 'eu-ch2'),
4361c4361
<                 this.akskAuthHeader = "Authorization", this.serviceMap = new Map(), this.cloud = t, t.region || (t.region = "eu-de", t.auth.project_name && (t.region = t.auth.project_name.split("_", 1)[0])), this.httpClient = new x({}), this.injectCommonHeaders(), this.registerService("identity", this.cloud.auth.auth_url);
---
>                 this.akskAuthHeader = "Authorization", this.serviceMap = new Map(), this.cloud = t, t.region || (t.region = "eu-ch2", t.auth.project_name && (t.region = t.auth.project_name.split("_", 1)[0])), this.httpClient = new x({}), this.injectCommonHeaders(), this.registerService("identity", this.cloud.auth.auth_url);
4605,4606c4605,4606
<                     projectName: 'eu-de',
<                     region: 'eu-de',
---
>                     projectName: 'eu-ch2',
>                     region: 'eu-ch2',
4624c4624
<                     availabilityZone: 'eu-de-01',
---
>                     availabilityZone: 'eu-ch2a',
```

**Comment by anton-sidelnikov** [comment]
Hi @tervor, currently we have problem with our API, we cannot support another region before implementing some APIs for regions, flavors and etc.

**Comment by tervor** [comment]
We realized, after posting the comment, that the compontnet.js only modifies the user interface and posted values, but the backend driver.go still has the authentication url hard-coded in https://github.com/opentelekomcloud/kontainer-engine-driver-otc/blob/e57b7310bee5c3e11b05ab3cce39a881b7b8ff36/opentelekomcloud/driver.go#L24-L31

@anton-sidelnikov What do you mean by "our API", the CCE api on OTC?
Our issue is that the authentication url for the Swiss OTC (region eu-ch2) differs from the authentication of the public OTC (region eu-de). So it should be a parameter to be passed from the rancher user interface (component.js).

**Comment by anton-sidelnikov** [comment]
@tervor yes CCE api on OTC, we are waiting for updates now. That's why there are many hardcoded items inside .js

**Comment by generalpax** [comment]
Any updates?

**Comment by anton-sidelnikov** [comment]
API still not updated, i will try to push backend team, and we also thinks inside our team how to add other regions support with some workarounds

**Comment by anton-sidelnikov** [comment]
Done, check Readme before using
